# Generated by Django 5.2.17 on 2026-08-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('adres', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Senet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('borc', 'Borç (Bizim Ödeyeceğimiz)'), ('alacak', 'Alacak (Bize Ödenecek)')], max_length=10)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vade_tarihi', models.DateField()),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('odendi', 'Ödendi'), ('gecikti', 'Gecikti')], default='bekliyor', max_length=10)),
                ('aciklama', models.CharField(blank=True, max_length=255, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senetler', to='accounts.firma')),
            ],
        ),
    ]
