# Generated by Django 5.2.17 on 2026-08-14 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('alis_fiyati', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satis_fiyati', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok_miktari', models.PositiveIntegerField(default=0)),
                ('kritik_stok_seviyesi', models.PositiveIntegerField(default=5)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='inventory.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='StokHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('giris', 'Stok Girişi'), ('cikis', 'Stok Çıkışı')], max_length=10)),
                ('miktar', models.PositiveIntegerField()),
                ('aciklama', models.CharField(blank=True, max_length=255, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='inventory.urun')),
            ],
        ),
        migrations.CreateModel(
            name='Barkod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barkod_no', models.CharField(max_length=50, unique=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barkodlar', to='inventory.urun')),
            ],
        ),
    ]
