# Generated by Django 5.2.17 on 2026-08-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('inventory', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='inventory.kategori'),
        ),
        migrations.AddConstraint(
            model_name='kategori',
            constraint=models.UniqueConstraint(fields=('parent', 'ad'), name='benzersiz_kategori_adi'),
        ),
    ]
