# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('inventory', '0002_kategori_parent')]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ('parent_id', 'ad')},
        ),
    ]
