# Generated by Django 5.2.17 on 2026-08-14 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('satisi_yapan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SatisKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField()),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='sales.satis')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.urun')),
            ],
        ),
    ]
