# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satis',
            name='odeme_yontemi',
            field=models.CharField(
                choices=[('nakit', 'Nakit'), ('kart', 'Kredi Kartı / POS')],
                default='nakit',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='satis',
            name='pos_islem_no',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
